apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmmanuell-backend
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  vault:
    enabled: true
    paths:
      - kvPath: /azuread/data/dev/creds/syfosmmanuell-backend
        mountPath: /secrets/azuread/syfosmmanuell-backend
      - kvPath: serviceuser/data/dev/srvsyfosmmanuell-backend
        mountPath: /secrets/serviceuser
      - kvPath: /kv/preprod/fss/syfosmmanuell-backend/default
        mountPath: /secrets/default
  webproxy: true
  ingresses:
    - "https://syfosmmanuell-backend.nais.preprod.local"
  env:
    - name: SYFOSMMANUELL_BACKEND_DB_URL
      value: jdbc:postgresql://b27dbvl009.preprod.local:5432/syfosmmanuell-backend
    - name: SERVICE_USER_USERNAME
      value: /secrets/serviceuser/username
    - name: SERVICE_USER_PASSWORD
      value: /secrets/serviceuser/password
    - name: MQ_USERNAME
      value: /secrets/default/mqUsername
    - name: MQ_PASSWORD
      value: /secrets/default/mqPassword
    - name: OID_WELL_KNOWN_URI
      value: /secrets/default/oidcWellKnownUri
    - name: SYFOSMMANUELL_BACKEND_CLIENT_ID
      value: /secrets/azuread/syfosmmanuell-backend/client_id
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss
    - name: SYFOSMMANUELL_URL
      value: syfosmmanuell.nais.preprod.local
    - name: MQ_SYFOSERVICE_QUEUE_NAME
      value: QA.Q1_EIA_SYFO_OUTBOUND
    - name: MQ_HOST_NAME
      value: b27apvl177.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQ1LSC04
    - name: MQ_CHANNEL_NAME
      value: Q1_SYFOSMMANUELL_B
    - name: JWT_ISSUER
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0
