apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmmanuell-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  gcp:
    sqlInstances:
      - name: syfosmmanuell-backend-instance
        type: POSTGRES_14
        tier: db-custom-2-5120
        diskSize: 100
        databases:
          - name: syfosmmanuell-backend
            envVarPrefix: DB
            users:
              - name: macgyver
        diskAutoresize: true
        highAvailability: true
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        pointInTimeRecovery: true
  image: {{ image }}
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  kafka:
    pool: nav-prod
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: syfosminfotrygd
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmmanuell
          namespace: teamsykmelding
          cluster: prod-gcp
    outbound:
      external:
        - host: syfo-tilgangskontroll.prod-fss-pub.nais.io
        - host: graph.microsoft.com
        - host: oppgave.prod-fss-pub.nais.io
  vault:
    enabled: false
  webproxy: false
  secureLogs:
    enabled: true
  env:
    - name: SYFOSMMANUELL_URL
      value: syfosmmanuell.intern.nav.no
    - name: SYFOTILGANGSKONTROLL_SCOPE
      value: api://prod-fss.teamsykefravr.syfo-tilgangskontroll/.default
    - name: SYFOTILGANGSKONTROLL_URL
      value: https://syfo-tilgangskontroll.prod-fss-pub.nais.io/syfo-tilgangskontroll
    - name: MS_GRAPH_API_URL
      value: https://graph.microsoft.com/v1.0
    - name: MS_GRAPH_API_SCOPE
      value: https://graph.microsoft.com/.default
    - name: OPPGAVE_SCOPE
      value: api://prod-fss.oppgavehandtering.oppgave/.default
    - name: OPPGAVEBEHANDLING_URL
      value: https://oppgave.prod-fss-pub.nais.io/api/v1/oppgaver
