apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmmanuell-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  gcp:
    sqlInstances:
      - name: syfosmmanuell-backend-instance
        type: POSTGRES_14
        diskSize: 10
        databases:
          - name: syfosmmanuell-backend
            envVarPrefix: DB
            users:
              - name: macgyver
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: "write,ddl,role"
          - name: pgaudit.log_parameter
            value: "on"
        pointInTimeRecovery: true
        tier: db-f1-micro
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: 50m
      memory: 756Mi
  kafka:
    pool: nav-dev
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: syfosminfotrygd
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syfosmmanuell
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: tsm-manuell-api
          namespace: tsm
          cluster: dev-gcp
    outbound:
      rules:
        - application: logging
          namespace: nais-system
        - application: istilgangskontroll
          namespace: teamsykefravr
          cluster: dev-gcp
      external:
        - host: graph.microsoft.com
        - host: oppgave-q1.dev-fss-pub.nais.io
        - host: teamsykmelding-unleash-api.nav.cloud.nais.io
  envFrom:
    - secret: syfosmmottak-unleash-api-token
  env:
    - name: SYFOSMMANUELL_URL
      value: syfosmmanuell.intern.dev.nav.no
    - name: ISTILGANGSKONTROLL_SCOPE
      value: api://dev-gcp.teamsykefravr.istilgangskontroll/.default
    - name: MS_GRAPH_API_SCOPE
      value: https://graph.microsoft.com/.default
    - name: MS_GRAPH_API_URL
      value: https://graph.microsoft.com/v1.0
    - name: OPPGAVE_SCOPE
      value: api://dev-fss.oppgavehandtering.oppgave-q1/.default
    - name: OPPGAVEBEHANDLING_URL
      value: https://oppgave-q1.dev-fss-pub.nais.io/api/v1/oppgaver
    - name: OPPGAVE_HENDELSE_TOPIC
      value: oppgavehandtering.oppgavehendelse-q1-v1
    - name: OPPGAVE_MAPPE_ID
      value: "100031565"
    - name: OPPGAVE_MAPPENAVN
      value: Tilbakedatert_trenger_mer_informasjon
    - name: OPPGAVE_ENHET
      value: "2820"
    - name: KAFKA_CLIENT_ID
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
