apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmmanuell-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  gcp:
    sqlInstances:
      - name: syfosmmanuell-backend-instance
        type: POSTGRES_14
        diskSize: 100
        databases:
          - name: syfosmmanuell-backend
            envVarPrefix: DB
            users:
              - name: macgyver
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        pointInTimeRecovery: true
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: 100m
      memory: 850Mi
  kafka:
    pool: nav-prod
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: syfosminfotrygd
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: syfosmmanuell
          namespace: teamsykmelding
          cluster: prod-gcp
    outbound:
      rules:
        - application: istilgangskontroll
          namespace: teamsykefravr
          cluster: prod-gcp
      external:
        - host: graph.microsoft.com
        - host: oppgave.prod-fss-pub.nais.io
  secureLogs:
    enabled: true
  env:
    - name: SYFOSMMANUELL_URL
      value: syfosmmanuell.intern.nav.no
    - name: ISTILGANGSKONTROLL_SCOPE
      value: api://prod-gcp.teamsykefravr.istilgangskontroll/.default
    - name: MS_GRAPH_API_URL
      value: https://graph.microsoft.com/v1.0
    - name: MS_GRAPH_API_SCOPE
      value: https://graph.microsoft.com/.default
    - name: OPPGAVE_SCOPE
      value: api://prod-fss.oppgavehandtering.oppgave/.default
    - name: OPPGAVEBEHANDLING_URL
      value: https://oppgave.prod-fss-pub.nais.io/api/v1/oppgaver
    - name: OPPGAVE_HENDELSE_TOPIC
      value: oppgavehandtering.oppgavehendelse-v1
    - name: OPPGAVE_MAPPE_ID
      value: "100026580"
    - name: OPPGAVE_MAPPENAVN
      value: Tilbakedatert sykmelding - Avventer dokumentasjon
    - name: OPPGAVE_ENHET
      value: "4488"
    - name: KAFKA_CLIENT_ID
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
