apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmmanuell-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
  vault:
    enabled: true
    paths:
      - kvPath: /azuread/data/prod/creds/syfosmmanuell-backend
        mountPath: /secrets/azuread/syfosmmanuell-backend
      - kvPath: serviceuser/data/prod/srvsyfosmmanuell-backend
        mountPath: /secrets/serviceuser
      - kvPath: /kv/prod/fss/syfosmmanuell-backend/teamsykmelding
        mountPath: /secrets/default
  webproxy: true
  ingresses:
    - "https://syfosmmanuell-backend.nais.adeo.no"
  env:
    - name: SYFOSMMANUELL_BACKEND_DB_URL
      value: jdbc:postgresql://A01DBVL010.adeo.no:5432/syfosmmanuell-backend
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443
    - name: MOUNT_PATH_VAULT
      value: /postgresql/prod-fss
    - name: SYFOSMMANUELL_URL
      value: syfosmmanuell.nais.adeo.no
    - name: JWT_ISSUER
      value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/token
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: dfaa2699-7390-4459-9cfc-2e8de64dfaf9
    - name: OPPGAVEBEHANDLING_URL
      value: https://oppgave.nais.adeo.no/api/v1/oppgaver
    - name: SYFOTILGANGSKONTROLL_URL
      value: https://syfo-tilgangskontroll.nais.adeo.no/syfo-tilgangskontroll
    - name: MS_GRAPH_API_SCOPE
      value: https://graph.microsoft.com/.default
    - name: MS_GRAPH_AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token