apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmmanuell-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: syfosmmanuell
          namespace: teamsykmelding
          cluster: dev-fss
        - application: syfosminfotrygd
  vault:
    enabled: true
    paths:
      - kvPath: /azuread/data/dev/creds/syfosmmanuell-backend
        mountPath: /secrets/azuread/syfosmmanuell-backend
      - kvPath: /kv/preprod/fss/syfosmmanuell-backend/teamsykmelding
        mountPath: /secrets/default
  webproxy: true
  ingresses:
    - "https://syfosmmanuell-backend.nais.preprod.local"
  env:
    - name: SYFOSMMANUELL_BACKEND_DB_URL
      value: jdbc:postgresql://b27dbvl009.preprod.local:5432/syfosmmanuell-backend
    - name: MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss
    - name: SYFOSMMANUELL_URL
      value: syfosmmanuell.dev.adeo.no
    - name: SYFOTILGANGSKONTROLL_SCOPE
      value: api://dev-fss.teamsykefravr.syfo-tilgangskontroll/.default
    - name: OPPGAVEBEHANDLING_URL
      value: https://oppgave-q1.nais.preprod.local/api/v1/oppgaver
    - name: SYFOTILGANGSKONTROLL_URL
      value: https://syfo-tilgangskontroll.nais.preprod.local/syfo-tilgangskontroll
    - name: MS_GRAPH_API_SCOPE
      value: https://graph.microsoft.com/.default
    - name: MS_GRAPH_API_URL
      value: https://graph.microsoft.com/v1.0
    - name: OPPGAVE_SCOPE
      value: api://dev-fss.oppgavehandtering.oppgave-q1/.default
