apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmmanuell-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: syfosmmanuell
          namespace: teamsykmelding
          cluster: prod-fss
        - application: syfosminfotrygd
  vault:
    enabled: true
  webproxy: true
  ingresses:
    - "https://syfosmmanuell-backend.nais.adeo.no"
  env:
    - name: SYFOSMMANUELL_BACKEND_DB_URL
      value: jdbc:postgresql://A01DBVL010.adeo.no:5432/syfosmmanuell-backend
    - name: MOUNT_PATH_VAULT
      value: /postgresql/prod-fss
    - name: SYFOSMMANUELL_URL
      value: syfosmmanuell.nais.adeo.no
    - name: SYFOTILGANGSKONTROLL_SCOPE
      value: api://prod-fss.teamsykefravr.syfo-tilgangskontroll/.default
    - name: OPPGAVEBEHANDLING_URL
      value: https://oppgave.nais.adeo.no/api/v1/oppgaver
    - name: SYFOTILGANGSKONTROLL_URL
      value: https://syfo-tilgangskontroll.nais.adeo.no/syfo-tilgangskontroll
    - name: MS_GRAPH_API_URL
      value: https://graph.microsoft.com/v1.0
    - name: MS_GRAPH_API_SCOPE
      value: https://graph.microsoft.com/.default
    - name: OPPGAVE_SCOPE
      value: api://prod-fss.oppgavehandtering.oppgave/.default
