apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmmanuell-backend
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  gcp:
    sqlInstances:
      - name: syfosmmanuell-backend-instance
        type: POSTGRES_14
        diskSize: 10
        databases:
          - name: syfosmmanuell-backend
            envVarPrefix: DB
            users:
              - name: macgyver
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: syfosmmanuell
          namespace: teamsykmelding
          cluster: dev-fss
        - application: syfosminfotrygd
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: syfosmmanuell
          namespace: teamsykmelding
          cluster: dev-gcp
  vault:
    enabled: false
  webproxy: false
  secureLogs:
    enabled: true
  ingresses:
    - "https://syfosmmanuell-backend.dev.nav.no"
    - "https://syfosmmanuell-backend.dev.intern.nav.no"
  env:
    - name: SYFOSMMANUELL_URL
      value: syfosmmanuell.dev.adeo.no
    - name: SYFOTILGANGSKONTROLL_SCOPE
      value: api://dev-fss.teamsykefravr.syfo-tilgangskontroll/.default
    - name: SYFOTILGANGSKONTROLL_URL
      value: https://syfo-tilgangskontroll.dev-fss-pub.nais.io/syfo-tilgangskontroll
    - name: MS_GRAPH_API_SCOPE
      value: https://graph.microsoft.com/.default
    - name: MS_GRAPH_API_URL
      value: https://graph.microsoft.com/v1.0
    - name: OPPGAVE_SCOPE
      value: api://dev-fss.oppgavehandtering.oppgave-q1/.default
    - name: OPPGAVEBEHANDLING_URL
      value: https://oppgave-q1.dev-fss-pub.nais.io/api/v1/oppgaver
